### ISSUE TITLE
custom callback for snap doesnt work

### ISSUE THREAD

**Issue by bimbimprasetyoafif** [veritrans/go-midtrans#80]
Hello

Documentation said we could use custom callback for our payment
[custom finish url](https://docs.midtrans.com/en/snap/advanced-feature?id=custom-finish-url)

when i tried to custom my payload like
`
Callbacks: &midtrans.Callbacks{
			Finish: "https://example.org/?foo=123456",
		},
`

instead of giving my custom finish url query, it still redirect with query
`
?status_code=200&transaction_status=settlement&merchant_id=XXXXXX&order_id=XXXXXXX
`

I used Development env for testing

**Comment by omarxp** [comment]
Hi @bimbimprasetyoafif thanks for reaching out.
please provide a sample order-id, so we can check further.

it's expected, we will add some params when redirect to finish url.

thank you.

**Comment by bimbimprasetyoafif** [comment]
Hi @omarxp , thanks for reply

I have done trying so many dummy. Maybe this sample order-id that i used could help you.
`B-DUMMY-1304218IKX`

**Comment by omarxp** [comment]
Hi @bimbimprasetyoafif 
after checking the order-id `B-DUMMY-1304218IKX` it uses bca_klikpay as the payment method.
following behavior from bca_klikpay and because redirection directly come from BCA (in production)
it's expected, query param will be ignore

if you need this value => `?foo=123456`
you can update finish URL to this => `https://example.org/foo-123456`

and when using bca_klikpay, please use snap popup instead of snap redirect.

please follow this link, how to use bca_klikpay:
https://support.midtrans.com/hc/en-us/articles/360024549814-What-if-I-want-to-use-BCA-Klikpay-as-a-payment-channel-
https://support.midtrans.com/hc/en-us/articles/115004580573-BCA-KlikPay-Landing-Page-Development-Guideline

thank you.

**Comment by bimbimprasetyoafif** [comment]
Thanks for your answer @omarxp 

Now I just figured out different between snap popup and snap redirect.

and about update finish url with `https://example.org/foo-123456` 
it become 
`https://example.org/foo-123456%25!(EXTRA%20string=B-DUMMY-140421DNQI)?order_id=B-DUMMY-140421DNQI&status_code=XXX&transaction_status=XXXXXX`

**Comment by omarxp** [comment]
snap popup: snap page will be shown on the merchant's website
snap redirect: redirect to midtrans domain

`!(EXTRA%20string=B-DUMMY-140421DNQI)` I guess it about format string, please check the implementation

thank you.

**Comment by rizdaprasetya** [comment]
Closed due to inactivity, please reply or submit the question via Midtrans support email if you still have further question. thanks.
